// Shared helpers for the Node build/database scripts. Plain ESM, no dependencies,
// so they run the same on Windows, macOS, Linux and Vercel's build image.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const MAIN_SCHEMA = path.join(ROOT, 'prisma', 'schema.prisma');
export const SQLITE_DIR = path.join(ROOT, 'prisma', 'sqlite');
export const SQLITE_SCHEMA = path.join(SQLITE_DIR, 'schema.prisma');
export const SQLITE_DB = path.join(SQLITE_DIR, 'stockflow.db');

const PRISMA_CLI = path.join(ROOT, 'node_modules', 'prisma', 'build', 'index.js');
const TSX_CLI = path.join(ROOT, 'node_modules', 'tsx', 'dist', 'cli.mjs');
const NEXT_CLI = path.join(ROOT, 'node_modules', 'next', 'dist', 'bin', 'next');

/**
 * Loads `.env` into process.env without overriding variables that are already set
 * (the real environment always wins, exactly like Next.js and the Prisma CLI).
 */
export function loadEnv() {
  const file = path.join(ROOT, '.env');
  if (!existsSync(file)) return;
  try {
    process.loadEnvFile(file);
  } catch (error) {
    console.warn(`[env] Could not parse .env: ${error.message}`);
  }
}

/** Normalises DATABASE_PROVIDER. Anything other than "sqlite" means PostgreSQL. */
export function getProvider() {
  const raw = (process.env.DATABASE_PROVIDER ?? '').trim().toLowerCase();
  return raw === 'sqlite' ? 'sqlite' : 'postgresql';
}

/**
 * Runs a Node CLI entry point with the current Node binary. Invoking the JS file
 * directly (instead of `npx`/a shell) sidesteps quoting problems with spaces in the
 * project path on Windows.
 */
function runNode(entry, args, { env, label } = {}) {
  const name = label ?? path.basename(entry);
  console.log(`\n> ${name} ${args.join(' ')}`);
  const result = spawnSync(process.execPath, [entry, ...args], {
    cwd: ROOT,
    stdio: 'inherit',
    env: { ...process.env, ...env },
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${name} ${args.join(' ')} exited with code ${result.status}`);
  }
}

export const prisma = (args, opts) => runNode(PRISMA_CLI, args, { label: 'prisma', ...opts });
export const tsx = (args, opts) => runNode(TSX_CLI, args, { label: 'tsx', ...opts });
export const next = (args, opts) => runNode(NEXT_CLI, args, { label: 'next', ...opts });

/**
 * Derives the SQLite schema from the main (PostgreSQL) schema:
 *   - datasource provider "postgresql" -> "sqlite", url -> the bundled database file
 *   - strips Postgres-only native type attributes such as @db.Decimal(10, 2)
 * Everything else (models, enums, indexes, relations) is portable as written.
 */
export function writeSqliteSchema() {
  const source = readFileSync(MAIN_SCHEMA, 'utf8');
  const datasource = /datasource\s+db\s*\{[^}]*\}/m;
  if (!datasource.test(source))
    throw new Error('No `datasource db { ... }` block in schema.prisma');

  const derived = source
    .replace(
      datasource,
      'datasource db {\n  provider = "sqlite"\n  url      = "file:./stockflow.db"\n}',
    )
    .replace(/\s@db\.\w+(\([^)]*\))?/g, '');

  const header =
    '// GENERATED by scripts/lib/common.mjs from prisma/schema.prisma - do not edit.\n' +
    '// SQLite variant used when DATABASE_PROVIDER=sqlite.\n\n';

  mkdirSync(SQLITE_DIR, { recursive: true });
  writeFileSync(SQLITE_SCHEMA, header + derived);
  return SQLITE_SCHEMA;
}

/** Generates the Prisma Client for the provider in use. */
export function generateClient(provider = getProvider()) {
  if (provider === 'sqlite') {
    writeSqliteSchema();
    prisma(['generate', `--schema=${SQLITE_SCHEMA}`]);
  } else {
    prisma(['generate', `--schema=${MAIN_SCHEMA}`]);
  }
}

/**
 * Builds a fresh SQLite database file from the derived schema and seeds it.
 * The file is what `next build` ships inside the serverless bundle.
 */
export function buildSqliteDatabase({ seed = true } = {}) {
  generateClient('sqlite');
  for (const suffix of ['', '-journal', '-wal', '-shm']) {
    rmSync(SQLITE_DB + suffix, { force: true });
  }
  prisma(['db', 'push', `--schema=${SQLITE_SCHEMA}`, '--skip-generate', '--accept-data-loss'], {
    env: { DATABASE_PROVIDER: 'sqlite' },
  });
  if (seed) {
    tsx(['prisma/seed.ts'], { env: { DATABASE_PROVIDER: 'sqlite' } });
  }
}
